"""Record-kind schema definitions for Loom.

Each entry defines the valid statuses, required sections, default status,
and output directory for one record kind.  The unified ``create`` command
and the ``diagnose`` command both import from here.
"""

from __future__ import annotations

SCHEMAS: dict[str, dict] = {
    "constitution": {
        "default_status": "active",
        "statuses": {"active", "revised", "superseded"},
        "sections": [
            "Vision",
            "Principles",
            "Constraints",
            "Strategic Direction",
            "Current Focus",
            "Open Constitutional Questions",
            "Change History",
        ],
        "output_directory": ".loom/constitution",
    },
    "decision": {
        "default_status": "active",
        "statuses": {"active", "revised", "superseded"},
        "sections": [
            "Decision",
            "Why This Decision Exists",
            "Alternatives Considered",
            "Consequences",
            "Supersession",
        ],
        "output_directory": ".loom/constitution/decisions",
        "file_slug_prefix": "decision",
        "auto_number_id": True,
    },
    "roadmap": {
        "default_status": "active",
        "statuses": {"active", "revised", "superseded"},
        "sections": [
            "Strategic Theme",
            "Why Now",
            "Focus Areas",
            "Milestones",
            "Sequencing Assumptions",
            "Downstream Work",
            "Status Summary",
        ],
        "output_directory": ".loom/constitution/roadmap",
        "id_from_slug": True,
    },
    "research": {
        "default_status": "active",
        "statuses": {"active", "revised", "superseded"},
        "sections": [
            "Question",
            "Objective",
            "Scope",
            "Non-goals",
            "Methodology",
            "Hypotheses",
            "Evidence",
            "Experiments",
            "Rejected Paths",
            "Conclusions",
            "Recommendations",
            "Open Questions",
            "Linked Downstream Artifacts",
        ],
        "output_directory": ".loom/research",
    },
    "initiative": {
        "default_status": "active",
        "statuses": {"active", "revised", "superseded"},
        "sections": [
            "Objective",
            "Why Now",
            "In Scope",
            "Out of Scope",
            "Success Metrics",
            "Milestones",
            "Dependencies",
            "Risks",
            "Linked Specs, Plans, and Tickets",
            "Status Summary",
        ],
        "output_directory": ".loom/initiatives",
    },
    "spec": {
        "default_status": "active",
        "statuses": {"active", "revised", "superseded"},
        "sections": [
            "Summary",
            "Problem Framing",
            "Desired Behavior",
            "Constraints",
            "Capabilities",
            "Requirements",
            "Scenarios",
            "Acceptance",
            "Design Notes",
            "Open Questions",
        ],
        "output_directory": ".loom/specs",
    },
    "plan": {
        "default_status": "draft",
        "statuses": {"draft", "active", "revised", "retired"},
        "sections": [
            "Purpose / Big Picture",
            "Progress",
            "Surprises & Discoveries",
            "Decision Log",
            "Outcomes & Retrospective",
            "Context and Orientation",
            "Milestones",
            "Plan of Work",
            "Concrete Steps",
            "Validation and Acceptance",
            "Idempotence and Recovery",
            "Artifacts and Notes",
            "Interfaces and Dependencies",
            "Linked Tickets",
            "Risks and Open Questions",
            "Revision Notes",
        ],
        "output_directory": ".loom/plans",
    },
    "ticket": {
        "default_status": "active",
        "statuses": {
            "proposed",
            "ready",
            "active",
            "blocked",
            "review_required",
            "complete_pending_acceptance",
            "closed",
            "cancelled",
        },
        "sections": [
            "Summary",
            "Context",
            "Why This Work Matters Now",
            "Scope",
            "Non-goals",
            "Acceptance Criteria",
            "Implementation Plan",
            "Dependencies",
            "Risks / Edge Cases",
            "Verification",
            "Documentation Disposition",
            "Journal",
        ],
        "output_directory": ".loom/tickets",
    },
    "critique": {
        "default_status": "active",
        "statuses": {"active", "revised", "superseded"},
        "sections": [
            "Target Under Review",
            "Review Question",
            "Focus Areas",
            "Relevant Context",
            "Evidence Reviewed",
            "Verdict",
            "Residual Risks",
            "Follow-up Tickets",
            "Findings Summary",
        ],
        "output_directory": ".loom/critique",
    },
    "doc": {
        "default_status": "draft",
        "statuses": {"draft", "accepted", "stale", "superseded"},
        "sections": [
            "Overview",
            "Audience",
            "Problem Framing",
            "Accepted System Shape",
            "Workflow / Operations Details",
            "Rationale",
            "Examples",
            "Verification Source",
            "Related Artifacts",
            "Supersession / History",
        ],
        "output_directory": ".loom/docs",
    },
    "verification": {
        "default_status": "recorded",
        "statuses": {"recorded"},
        "sections": [
            "Summary",
            "Command",
            "Evidence",
            "Outcome",
            "Related Artifacts",
        ],
        "output_directory": ".loom/verification",
    },
}
