from __future__ import annotations


def block_markers(block_id: str) -> tuple[str, str]:
    begin = f"<!-- BEGIN:compound:{block_id} -->"
    end = f"<!-- END:compound:{block_id} -->"
    return begin, end


def _normalize_newlines(text: str) -> str:
    return str(text or "").replace("\r\n", "\n")


def managed_block(block_id: str, inner: str) -> str:
    begin, end = block_markers(block_id)
    body = _normalize_newlines(inner).rstrip()
    return "\n".join([begin, body, end])


def read_managed_block_inner(doc: str, block_id: str) -> str:
    text = _normalize_newlines(doc)
    begin, end = block_markers(block_id)
    b = text.find(begin)
    e = text.find(end)
    if b == -1 or e == -1 or e <= b:
        return ""
    return text[b + len(begin) : e].strip()


def upsert_managed_block(doc: str, block_id: str, inner: str) -> str:
    text = _normalize_newlines(doc)
    begin, end = block_markers(block_id)
    block = managed_block(block_id, inner)

    b = text.find(begin)
    e = text.find(end)
    if b != -1 and e != -1 and e > b:
        before = text[:b]
        after = text[e + len(end) :]
        return (before + block + after).rstrip() + "\n"

    trimmed = text.rstrip()
    if not trimmed:
        return block.rstrip() + "\n"
    return trimmed + "\n\n" + block.rstrip() + "\n"


def remove_managed_block(doc: str, block_id: str) -> str:
    text = _normalize_newlines(doc)
    begin, end = block_markers(block_id)
    b = text.find(begin)
    e = text.find(end)
    if b == -1 or e == -1 or e <= b:
        return text
    before = text[:b].rstrip()
    after = text[e + len(end) :].lstrip()
    if before and after:
        return (before + "\n\n" + after).rstrip() + "\n"
    return (before or after).rstrip() + "\n"


def is_placeholder_block(inner: str) -> bool:
    t = _normalize_newlines(inner).strip()
    if not t:
        return True
    if t == "(autogenerated)":
        return True
    if t.lower() == "(auto-generated)":
        return True
    if t.lstrip().startswith("- _(") and "none" in t.lower():
        return True
    return False


def upsert_managed_block_preserving_non_placeholder(
    doc: str, block_id: str, inner: str
) -> str:
    existing = read_managed_block_inner(doc, block_id)
    if existing and not is_placeholder_block(existing):
        return _normalize_newlines(doc).rstrip() + "\n"
    return upsert_managed_block(doc, block_id, inner)
