from __future__ import annotations

import contextlib
from pathlib import Path

from agent_loom.compound.models import CompoundInstallResult
from agent_loom.pack.core import install_pack, update_pack
from agent_loom.pack.lock import index_packs, load_lock


COMPOUND_PACK_ID = "loom-compound-core"


def _read_text_if_exists(p: Path) -> str:
    with contextlib.suppress(OSError):
        return p.read_text(encoding="utf-8")
    return ""


def _ensure_doc_fences(text: str, *, ids: list[str]) -> tuple[str, bool]:
    changed = False
    out = text
    for ident in ids:
        begin = f"<!-- BEGIN:compound:{ident} -->"
        end = f"<!-- END:compound:{ident} -->"
        if begin in out and end in out:
            continue
        changed = True
        out = (
            out.rstrip()
            + "\n\n"
            + "\n".join([begin, "(autogenerated)", end, ""])  # trailing newline
        )
    return out, changed


def _pack_installed(repo_root: Path, *, pack_id: str) -> bool:
    try:
        lock = load_lock(repo_root)
    except Exception:
        return False
    return pack_id in index_packs(lock)


def install_opencode(
    *, dest: Path, dry_run: bool, force: bool = False
) -> CompoundInstallResult:
    """Install/upgrade Compound's repo scaffold via Loom packs.

    Contract (kept compatible with the previous installer):
    - Installs/updates OpenCode integration under `.opencode/**`.
    - Creates baseline docs under `LOOM.md` + `.loom/compound/**` if missing.
    - Never overwrites `AGENTS.md`, `LOOM.md`, or `.loom/compound/**` once present.
    - Ensures required compound doc fences exist in `LOOM.md` and `.loom/compound/ROADMAP.md`.
    """

    repo_root = dest.expanduser().resolve()

    wrote: list[str] = []
    skipped: list[str] = []
    warnings: list[str] = []

    if _pack_installed(repo_root, pack_id=COMPOUND_PACK_ID):
        pr = update_pack(
            repo_root=repo_root,
            pack_id=COMPOUND_PACK_ID,
            dry_run=bool(dry_run),
            force=bool(force),
        )
    else:
        pr = install_pack(
            repo_root=repo_root,
            pack_id=COMPOUND_PACK_ID,
            dry_run=bool(dry_run),
            force=bool(force),
        )

    wrote.extend(list(pr.wrote or []))
    skipped.extend(list(pr.skipped or []))
    warnings.extend(list(pr.warnings or []))

    # Ensure LOOM doc fences exist (idempotent; never overwrites full docs).
    doc_specs: list[tuple[str, list[str]]] = [
        (
            "LOOM.md",
            [
                "agents-ai-behavior",
                "loom-commands",
                "loom-core-context",
                "instincts-index",
            ],
        ),
        (
            ".loom/compound/ROADMAP.md",
            ["roadmap-backlog", "roadmap-ai-notes", "changelog-entries"],
        ),
    ]

    for rel, required_ids in doc_specs:
        p = repo_root / rel
        if not p.exists():
            # The pack should have created this if missing, but be conservative.
            continue

        raw = _read_text_if_exists(p)
        new, changed = _ensure_doc_fences(raw, ids=required_ids)
        if not changed:
            continue

        if dry_run:
            wrote.append(rel)
        else:
            p.write_text(new, encoding="utf-8")
            wrote.append(rel)

    return CompoundInstallResult(
        dest=str(repo_root),
        dry_run=bool(dry_run),
        wrote=sorted(set(wrote)),
        skipped=sorted(set(skipped)),
        warnings=sorted(set(warnings)),
    )


__all__ = [
    "install_opencode",
]
