from __future__ import annotations

from agent_loom.team.cli import main as cli
from agent_loom.team.core import (
    attach,
    bounce,
    capture,
    disband,
    done,
    inbox_ack,
    inbox_list,
    inbox_send,
    inbox_show,
    init_agents,
    janitor,
    mark_retirable,
    merge_done,
    merge_enqueue,
    merge_list,
    merge_next,
    objective_append,
    objective_set,
    objective_show,
    pause_team,
    prep_sprint,
    resume_team,
    resume_worker,
    retire,
    send,
    ship,
    spawn,
    spawn_integrator,
    start,
    status,
    tui,
    wait,
)
from agent_loom.team.prime import prime

__all__ = [
    "cli",
    "init_agents",
    "prime",
    "attach",
    "bounce",
    "capture",
    "disband",
    "pause_team",
    "done",
    "inbox_ack",
    "inbox_list",
    "inbox_send",
    "inbox_show",
    "janitor",
    "mark_retirable",
    "prep_sprint",
    "merge_done",
    "merge_enqueue",
    "merge_list",
    "merge_next",
    "objective_append",
    "objective_set",
    "objective_show",
    "retire",
    "resume_team",
    "resume_worker",
    "send",
    "ship",
    "spawn",
    "spawn_integrator",
    "start",
    "status",
    "tui",
    "wait",
]
